name: WordsOfWorld
options:
  bundleIdPrefix: com.rimuruai
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"
targets:
  WordsOfWorld:
    type: application
    platform: macOS
    sources:
      - WordsOfWorld
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rimuruai.words-of-world
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "-"
      INFOPLIST_FILE: WordsOfWorld/Info.plist
      CODE_SIGN_ENTITLEMENTS: WordsOfWorld/WordsOfWorld.entitlements
    dependencies:
      - sdk: Carbon.framework
      - sdk: UserNotifications.framework
  WordsOfWorldTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - WordsOfWorldTests
    settings:
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    dependencies:
      - target: WordsOfWorld
